# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7190a4113d5145aa4854c22cba6d510fb8fa80c0cbc30645fd9915c103687edd01d65abc661f7f393f90ab421613c11fee0cb0765c20bd53c3c9819ed9830fb5

test:
  secret_key_base: a3cb3adb6d53163b136542d7bf04da4caa99cbc814391a95637e45a82f9ea58861eb21124f6330e46c8bcd55d66f01c4958d8cf4313b99a04a8a38fc2abd73b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
